### ISSUE TITLE
Missing translation for the facet column mobile "Filters" button label

### ISSUE THREAD

**Issue by jflheureux** [coveo/search-ui#756]
In the [ResponsiveFacetColumn](https://github.com/coveo/search-ui/blob/master/src/ui/ResponsiveComponents/ResponsiveFacetColumn.ts) component, the Filters button that is displayed on mobile devices is using a string dictionary key of "Filters". However, this string is not translated in the [strings.json](https://github.com/coveo/search-ui/blob/master/strings/strings.json) file.

Can it be translated in all languages please?

**Comment by olamothe** [comment]
Hello,

We do translation by hiring different translator for each language from time to time, whenever there's a sizable amount of new strings that needs translation.

Unfortunately, asking for new translation for only a small amount of new strings (I currently count only 15 strings to would need to be translated in languages other than french and english) is too time consuming to be really worth it for now.

If you know other languages than those we do ourselves manually (french and english), feel free to contribute !
